(cl:defpackage sc_msgs-srv
  (:use )
  (:export
   "GETPARAMLIST"
   "<GETPARAMLIST-REQUEST>"
   "GETPARAMLIST-REQUEST"
   "<GETPARAMLIST-RESPONSE>"
   "GETPARAMLIST-RESPONSE"
   "SETPARAMLIST"
   "<SETPARAMLIST-REQUEST>"
   "SETPARAMLIST-REQUEST"
   "<SETPARAMLIST-RESPONSE>"
   "SETPARAMLIST-RESPONSE"
  ))

